
services:
  cron_service:
    build: .
    container_name: cron_container
    restart: unless-stopped
    environment:
      - TZ=Europe/Berlin
      - DATA_DIR=/tmp/selenium_profile
      - REMOTE_DRIVER=http://selenium:4444/wd/hub
    volumes:
      - ./prev_elems.data:/tmp/prev_elems.data:rw
    depends_on:
      - selenium
  selenium:
    image: selenium/standalone-chromium
    container_name: selenium_container
    restart: unless-stopped
    shm_size: 2g
    volumes:
      - ./selenium_profile:/tmp/selenium_profile:rw